pipeline {
  options {
    timeout(time: 60, unit: 'MINUTES')
  }

  environment {
    IMAGE_NAME = 'static-ws'
    IMAGE_REL = 'v1r0'
    CONTAINER_NAME = 'container-static-ws'
    TEST_LOCAL_PORT = 8081
  }
  
  triggers {
    cron('0 1 * * 1-5')
  }

    agent { node { label 'master' } }
  
  stages {
    stage('Step 1') {
steps{
      echo "Step 1"
    
//      git branch: "main",
//	credentialsId: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvjMIhXqa1o40CrmAgYpIWsC1aV2u5xwiUpUmz+rnVam4/UUwhczBaaOY9jFRj6IN38PVXNqgkMoevVPqasraz6G4SgX463fcmiKe+b1EwhROhnG6q+ho5TEzz2yzJPaqUyN6skhJAqsBCuZ4Lpt9utag0hTSdN4SSvnPR8duER07oT3UvCDmXHdPLvdlHqzbFdXzjndS0h6a7D4yVSqnzPlbROCZ6pF0NiKyt0u3O2u6aeb7zs8K1Ee0ps921vpUSwcQpR8x09kX3yIuqCGDlvdQ8/2tTf9XAeML2JF68T9lXqkwi/RD2xdWaZiW5Fdxfj0GbgwtQ2d+HA/rhnjXa8mjx9MmA+GwJcU0FWPAWHW6m9sa/GGtKRIHQ8S9KKDTWk8dptP7BMJvoX2rPRjl07BqwhUXRtS8J8mg+56eRpDtvQCJU8nsvnv8HWi3vPsnyBejpuCffBLG6yov7gjHhyWQYo2/GMBWyc2YD0SBoL8kI0FJWoeKWEfLh4AIGIaE= yamataw@devops",
  //      url: 'git@github.com:Yamataw/cicd-static-website-main.git'
    }}
    stage('Step 2') {
steps{
      sh "docker build -t ${IMAGE_NAME}:${IMAGE_REL} -f ../docker/Dockerfile"
      sh "[ -z \"\$(docker ps -a | grep ${CONTAINER_NAME} 2>/dev/null)\" ] || docker rm -f container-static-ws"
      sh "docker run --detach --name ${CONTAINER_NAME} --rm --publish ${TEST_LOCAL_PORT}:80 ${IMAGE_NAME}:${IMAGE_REL}"
    }}
    stage('Step 3') {
      steps {
        script {
          final String url = "http://localhost:${TEST_LOCAL_PORT}/index.html"
          final def (String response, int code) =
                            sh(script: "curl -s -w '\\n%{response_code}'", returnStdout: true)
                                .trim()
                                .tokenize("\n")

          echo "HTTP response status code: $code"

          if (code == 200) {
            echo response
          }
        }
      }
    }
  }
}
